image: moodlehq/moodle-workplace-plugin-ci:8.0

services:
  - postgres:13
  #- mysql:5.7.26
  - name: selenium/standalone-chrome:3
    alias: selenium-standalone-chrome

variables:
  MOODLE_REPO_WORKPLACE: git@git.in.moodle.com:workplace/workplacedev.git
  MOODLE_BRANCH_WORKPLACE401R: master
  MOODLE_BRANCH_WORKPLACE401S: WORKPLACE_401
  MOODLE_BRANCH_WORKPLACE400: WORKPLACE_400
  MOODLE_REPO_LMS: git@git.in.moodle.com:moodle/moodle.git
  MOODLE_BRANCH_LMS400: MOODLE_400_STABLE
  MOODLE_BRANCH_LMS401: MOODLE_401_STABLE
  MOODLE_BRANCH_LMS402: MOODLE_402_STABLE
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  DB: "pgsql"
#  DB: "mysqli"
  MUSTACHE_IGNORE_NAMES: 'mobile*.mustache'

# Gitlab-ci does not have matrixes, so we have these hidden jobs .setupworkplace and .setuplms to do the set up.
.setupworkplace: &setupworkplace
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE401R
    - . prepare-workplace $cibot_sshkey
    - cd $CI_PROJECT_DIR/..
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-theme_workplace.git
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_wp.git
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_certificate.git
    - moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
    - cd moodle

codecheck:
  <<: *setupworkplace
  script:
    - php admin/tool/phpunit/cli/init.php
    - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
    - . check-start
    - . check version_number
    - . check no_workplace_licenses
    - . check this_plugin_is_part_of "the mod_coursecertificate plugin for Moodle - http://moodle.org/" --nowplicensecomment
    - . check language_file_sorting
    - . check behat_workplace_tag
    - . check moodle-plugin-ci phplint
    #- . check moodle-plugin-ci phpcpd
    #- . check moodle-plugin-ci phpmd
    - . check moodle-plugin-ci codechecker --max-warnings 0
    - . check moodle-plugin-ci phpdoc
    - . check moodle-plugin-ci validate
    - . check moodle-plugin-ci savepoints
    - . check moodle-plugin-ci mustache
    - . check moodle-plugin-ci grunt --max-lint-warnings 0
    - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite tool_dataprivacy_testsuite --filter metadata_registry_test
    - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_testsuite --filter test_all_external_info
    - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_test
    - . check moodle-plugin-ci phpunit --coverage-text --fail-on-warning
    - . check-finish
  except:
    - tags

behat:
  <<: *setupworkplace
  script:
    - php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
    - php admin/tool/behat/cli/init.php --add-core-features-to-theme --parallel=3 --optimize-runs=@mod_coursecertificate
    - . check-start
    - . check moodle-plugin-ci behat --suite workplace --profile chrome
    - . check-finish
  except:
    - master
    - tags

.scriptshorttest: &scriptshorttest
  script:
    - . prepare-workplace $cibot_sshkey
    - cd $CI_PROJECT_DIR/..
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_certificate.git
    - |
      if [ "$INCLUDERB" == "1" ]; then
        moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_tenant.git --branch $MOODLE_BRANCH
        moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_wp.git --branch $MOODLE_BRANCH
        moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_reportbuilder.git --branch $MOODLE_BRANCH
      fi
    - moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
    - cd moodle
    - php admin/tool/phpunit/cli/init.php
    - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
    - php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
    - php admin/tool/behat/cli/init.php --add-core-features-to-theme --parallel=3 --optimize-runs=@mod_coursecertificate
    - . check-start
    - . check moodle-plugin-ci phpunit --coverage-text --fail-on-warning
    - . check moodle-plugin-ci behat --suite default --profile chrome
    - . check-finish

wp401s:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE401S
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

wp400:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE400
    - export INCLUDERB=1
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms400:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS400
  <<: *scriptshorttest
  except:
    - master
    - tags

lms401:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS401
  <<: *scriptshorttest
  except:
    - master
    - tags

lms402:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS402
  <<: *scriptshorttest
  except:
    - master
    - tags
